# To install: conda env create -f environment.yml
#
# To check that it's working: python -c "import torch; print(torch.cuda.is_available())"
#
# Ref: https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md
name: PAT-Pipeline-for-Analysis-of-Periderm

channels:
  - conda-forge
  - defaults
  - pytorch
  - fvcore
  - iopath
  - pytorch3d

dependencies:
  - python=3.8
  - ipykernel
  - pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch3d
  - ffmpeg
  - nodejs
  - pip
  - pip:
    - matplotlib
    - pandas
    - seaborn
    - ipywidgets
    - rich
    - scikit-learn
    - albumentations
    - opencv-python
    - opencv-python-headless
    - segmentation_models_pytorch
    - PyQt5
    - fil_finder
